# This file determines the settings of your jupyterhub
# if u want a bettter idea of what the code is doing, check out the web links

# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html
proxy:
  secretToken: "a448f62bc2fe75c8918624fd2718933bf50c77a228077ca873a57cb86bf60976"
hub:
  # output of first execution of 'openssl rand -hex 32'
  cookieSecret: "35e5323d8f646eea4b2455890b7354ad625589d8a88d0c0eae7b00a116216ddd"
