# This file determines the settings of your jupyterhub
# if u want a bettter idea of what the code is doing, check out the web links

# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html
proxy:
  secretToken: "65984d30e7a15b72280bc3b3c1edbab11c820a4c05c2b539f0b8ec6c35ae646f"
hub:
  # output of first execution of 'openssl rand -hex 32'
  cookieSecret: "65984d30e7a15b72280bc3b3c1edbab11c820a4c05c2b539f0b8ec6c35ae646f"
